version: "3.8"
services:
  frontend:
    image: jungsupark/harmonai-fe:latest
    ports:
      - "5173:80"
    depends_on:
      - beserver
    networks:
      - app-network

  se:
    image: testimage
    ports:
      - "8088:8080"
    networks:
      - app-network

  beserver:
    image: hyuunminn/aiserver
    ports:
      - "8080:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
