name: harmonai dev CI/CD Pipeline

# 트리거
on:
  push:
    branches:
      - main

# 작업
jobs:
  build:
    runs-one: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # JDK 설치
      - name: Set up JDK 21
        uses: actions/setup@V2
        with:
          java-version: 21

      # Gradle Build
      - name: Build with Gradle
        run: ./gradlew build

      #DockerHub 로그인
      - name: hyuunminn
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/didacto-app-dev .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/didacto-app-dev
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # AWS 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd hyuunminn-beserver
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi hyuunminn/beserver:latest
            sudo docker-compose up -d